### ISSUE TITLE
implement display criterion

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#194]
On the front page we should not display points that have been imported but don't pass this test: https://github.com/tosdr/tosdr-build/blob/master/build/buildIndexes.js#L63-L67
When logged in, these points should still be visible though (and probably even made extra visible if they are points that haven't been curated or moderated yet)

**Comment by michielbdejong** [comment]
See also https://github.com/tosdr/tosdr-build/blob/master/scripts/curator.js#L89

**Comment by piks3l** [comment]
I do agree, displayed point should be analysed points with some data. Maybe we could add a little message for point that don't have enough data such as "this services lacks of analysis, help expanding it". 

On the status es, we found it very confusing between the different status that existed. So here what Phoenix has:
* pending : a point is submitted by a user and not reviewed by a curator
* approved : a point is approved and can be displayed on the service's page
* disputed : a point has already been submitted but needs more attention from another curator, because of reasons
* draft : a point hasn't been fully submitted by a user, s/he wants to work more on it
* declined : a point has been refused

More importantly, while submitting a point, there should be information on what info is required for what etc. Currently, it's very basic and I guess to improve the UX, we should be able to add hovers to the fields with more info (I can take care of that). Or ask maybe @jancborchardt if he could help us improving the UX for the submitting process.

**Comment by michielbdejong** [comment]
I think the translation should be:
has a point&score-> approved
disputed -> disputed
irrelevant / !binding -> declined
otherwise -> pending

**Comment by piks3l** [comment]
So,
A user adds a point, its status is pending.
Curator can: 
* if the point is good, => approved
* if the point needs more attention => discussed
* if the point is irrelevant, incomplete => declined

I think we didn't use the binding option in the original schema of phoenix because, in the current model, we thought it would be complicated for user to take the difference between a binding and a non-binding point. We started from the understanding that everything in the ToS of a service is binding as it is a contract. What was the original idea of this option?

**Comment by michielbdejong** [comment]
I think you mean 'disputed', not 'discussed'?

I also never really understood the 'binding' field, I think it was meant to express that some points come from a specific paragraph (binding) and others are just historical observations (non-binding), for instance "This site appears on https://www.eff.org/who-has-your-back-2017" - something we want to mention but that came from some other source than the site's ToS.

Anyway, I agree we don't need it. I'm updating the import script so that point status gets set correctly.

**Comment by piks3l** [comment]
disputed yes, sorry :) thanks for the explanation !
