### ISSUE TITLE
Edit is a bit slow, is there some improivements we could make ?

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#258]

**Comment by madoleary** [comment]
Do you mean like edit.tosdr.org in general or the functionality for editing a point? for the application overall, i think some of the views could definitely be refactored. dump the lists and whatnot into partials and store data in the controllers so it doesn't have to load with the html.erb files. i can work on this, just let me know what you think.

**Comment by piks3l** [comment]
Sounds good ! I was also looking into upgrading the performance of the server but as we are currently on heroku it has some limitations. This sounds actually like a good idea and a good first step. I planned also to look into that : https://medium.com/@rachelchervin/a-beginners-guide-to-heroku-rails-postgres-database-memory-optimization-6c9969516a4d

**Comment by piks3l** [comment]
I've added a compression of assets in production [link](https://github.com/romanbsd/heroku-deflater)

I ran also few tests on the memory consumption with [Mini Profiler](https://github.com/MiniProfiler/rack-mini-profiler) and here are the results:

```
==================================
  Mode: wall(1000)
  Samples: 12403 (0.85% miss rate)
  GC: 1135 (9.15%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      1407  (11.3%)        1407  (11.3%)     Rack::MiniProfiler.config
      2647  (21.3%)        1202   (9.7%)     Rack::MiniProfiler::TimerStruct::Sql#initialize
      1135   (9.2%)        1135   (9.2%)     (garbage collection)
      3273  (26.4%)         542   (4.4%)     PG::Connection#async_exec
       354   (2.9%)         354   (2.9%)     Sprockets::Mime#compute_extname_map
       293   (2.4%)         293   (2.4%)     Regexp#match?
       223   (1.8%)         202   (1.6%)     ActiveRecord::AttributeMethods::PrimaryKey::ClassMethods#primary_key
       226   (1.8%)         185   (1.5%)     Logger::LogDevice#write
       180   (1.5%)         180   (1.5%)     ActiveRecord::Base.logger
       538   (4.3%)         172   (1.4%)     ActiveRecord::DynamicMatchers#respond_to_missing?
       150   (1.2%)         150   (1.2%)     ActiveRecord::DynamicMatchers::Method.pattern
       150   (1.2%)         150   (1.2%)     ActiveSupport::Callbacks::CallTemplate#expand
       209   (1.7%)         145   (1.2%)     ActiveRecord::LazyAttributeHash#[]
       338   (2.7%)         138   (1.1%)     ActiveRecord::AttributeSet#[]
       144   (1.2%)         136   (1.1%)     Bullet::Registry::Association#similarly_associated
       134   (1.1%)         134   (1.1%)     String#bullet_class_name
       132   (1.1%)         132   (1.1%)     block (4 levels) in class_attribute
       125   (1.0%)         125   (1.0%)     ActiveRecord::Transactions#update_attributes_from_transaction_state
       150   (1.2%)         120   (1.0%)     block (2 levels) in class_attribute
       753   (6.1%)         117   (0.9%)     Object#bullet_key
       107   (0.9%)         105   (0.8%)     Set#merge
        96   (0.8%)          96   (0.8%)     ActiveRecord::Attribute#initialize
        89   (0.7%)          89   (0.7%)     URI::RFC3986_Parser#split
        90   (0.7%)          84   (0.7%)     ActiveRecord::QueryMethods#default_value_for
        80   (0.6%)          80   (0.6%)     Bullet::Registry::Base#[]
        74   (0.6%)          74   (0.6%)     Concurrent::Collection::NonConcurrentMapBackend#[]
        68   (0.5%)          68   (0.5%)     Set#include?
        81   (0.7%)          65   (0.5%)     ActiveModel::AttributeMethods::ClassMethods#define_proxy_call
        75   (0.6%)          59   (0.5%)     ActiveSupport::Inflector#underscore
        53   (0.4%)          53   (0.4%)     Bullet::Detector::Association.call_object_associations
```

I feel like our biggest bottleneck is the access to the Postgres database, but I'm not yet an expert in interpreting this...

**Comment by piks3l** [comment]
I ran Phoenix on https://developers.google.com/speed/pagespeed and the score is really bad there as well. [See](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fedit.tosdr.org%2F&tab=desktop)

**Comment by Psycojoker** [comment]
Hello,

@piks3l's friend here. I'm not a rails developer but I've a been a web django (python) developer since years and you are probably runnning in the same problems than everyone for performances. 

In 95% of the case, the first thing you'll want to optimize is the database access by first reducing the number of queries then optimizing the remaining one. 

Since you are using an ORM like everyone else, you are probably running in the infamous "n+1 queries".  The basic idea is that if you have a situation like:

- have a record that is a blog post
- have a record that are comments linked to a blog post

If you do something like (pseudo code):

```ruby
for comment in blog_post.comments
    comment.content
end
```

Every time you do "comment.content" you'll do another SQL query which will give you "1 sql query for the post * number of comment additional sql queries" which makes things very slow. Instead you'll want to have only one SQL query for the whole.

This post seems good at explaining it and giving tips to solve it https://medium.com/@User3141592/active-record-query-performance-tips-a3c3947b968 (don't forget I'm not a rails dev)

I don't know what are the tools in rails to detect those apart from reading the code (you'll probably wants to print the runt SQL queries if anything else), in django we uses the [django debug toolbar](https://camo.githubusercontent.com/577d78f4c1fdb33761f2c8e541909c117a67f8ee/68747470733a2f2f7261772e6769746875622e636f6d2f6a617a7a62616e642f646a616e676f2d64656275672d746f6f6c6261722f6d61737465722f6578616d706c652f646a616e676f2d64656275672d746f6f6c6261722e706e67) for that. I don't know what's the equivalent or way of doing that in rails, apparently there is this chromium extension that does that https://github.com/dejan/rails_panel

Once you have optimized and removed as much as possible all the n+1 problems (that's going to be your main problem most of the time and you'll see great improvement pretty quickly), you'll want to profile the exact code to see what remains to be optimised if there is. And once and once you'll get in a situation where there is nothing left to optimized, you can start to look at caching. But that's a delicate subject and it's really easy to introduce bugs that are very very hard to tract down because cache invalidation can be very tricky :/

Oh and if it's not obvious you'll want to work on a "page by page" basis, look at the website as a whole is not very pertinent for now.

Good luck :heart:
