### ISSUE TITLE
Bug: Cannot see the Feature option in the menu in production

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#350]
Needs investigation

**Comment by madoleary** [comment]
I don't get it. I don't have a problem with feature vs un-feature for these points.

**Comment by piks3l** [comment]
Err... I guess it's because there are points that are featured but not approved, I got confused on different things maybe...

**Comment by michielbdejong** [comment]
@piks3l only points with status 'Approved' can be featured and unfeatured. That makes sense, because if a point is not approved, it's not visible, and so it cannot act as a featured point?

The code that does this is here: https://github.com/tosdr/phoenix/blob/master/app/views/points/show.html.erb#L17-L23

**Comment by piks3l** [comment]
Yes, that makes sense... But if it just happens to me, no need to keep the issue open :)

**Comment by michielbdejong** [comment]
For 1062 I can see the 'Unfeature' option, and 2102 has status 'diputed', see screenshots.

So it looks like this is working correctly, please reopen if there is new information on this.
<img width="427" alt="screen shot 2018-05-25 at 15 26 08" src="https://user-images.githubusercontent.com/408412/40546617-00198fbe-6030-11e8-8806-39b56873612e.png">
<img width="686" alt="screen shot 2018-05-25 at 15 25 51" src="https://user-images.githubusercontent.com/408412/40546618-0041bdd6-6030-11e8-97d6-75914e978eab.png">
