### ISSUE TITLE
Cases should not be able to have an empty description

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#418]
Submitting a point fails when it is linked to a case without a description, because that description is used for the analysis field, which should not be left blank. (Moreover, this fails without a user-facing error message.)

**Comment by Vinnl** [comment]
@michielbdejong Could you take a look at this? (Since you added the cases functionality :) )

**Comment by madoleary** [comment]
I worked on cases. This is an interesting problem, since the initial philosophy was to not allow for points without analyses. If cases are points, then why do we allow cases without descriptions? On one hand, I could make some type of re-direct that allows users to fill in their own descriptions for a description-less cases, but that would seem to defeat the uniform nature of cases. But I also don't see value in allowing for points without analyses by removing the validation that requires analyses in the first place. @michielbdejong @piks3l -- thoughts?

**Comment by michielbdejong** [comment]
I think every point should have a case (if a user creates a point from scratch, we silently add an entry in the cases table to keep this consistent in the database), and the point should always use the topic and rating of the point, but can override the title, and the description/analysis. The point should also add the quote ('source').

For title and description/analysis, the default can be that they are taken from the case (or the cases-table-entry that is generated on the fly if the point is created from scratch), but it should also be possible to customize both of them, for instance to give a more specific description, or to rephrase it with the name of the service mentioned.

So indeed, I think cases should not be allowed to have an empty description.

**Comment by piks3l** [comment]
Agreed with @michielbdejong :)

**Comment by madoleary** [comment]
If we want the user to be able to edit the description and title during the point submission process via cases, then that will need to be made available on the shorter case submission form, which I can work on. 

I have a remaining question, however. How do we prevent overlap between points made from scratch and cases, in the event the user doesn't review all available cases? This seems like a likely issue, since, in my experience reading terms of service agreements, many of them convey the same messages, but using very different language.

**Comment by michielbdejong** [comment]
> How do we prevent overlap [...] in the event the user doesn't review all available cases?

Good question! One thing we can do is suggest cases based on the quote. That was one reason I wanted to store the quoteText in the Point table in the database. So when you submit a point, you now have to select the quote, and then it should display suggested Cases based on other points whose quoteText is similar based on trigram distance.

**Comment by Vinnl** [comment]
I think this is irrelevant now that all points have cases, and no longer have a separate description. Is that correct? If not, please re-open this issue.

**Comment by madoleary** [comment]
yeah i don't think that is correct. i thought we wanted users to be able to
add their own descriptions, if they want to make one that differs from the
case's.
