### ISSUE TITLE
Annotate toast is empty if no annotatable points are available

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#572]
For instance http://localhost:3000/services/325/annotate

Follow-up from #556.

The review flow is now also weird, but that's a bit of an artefact from having so many points without quotes in the database, which we need to go through first.

## setup:
* create service
* hand-type url to create documents
* assign that service to created documents
* from viewing the service, go to 'annotate docs'

## annotation process:
* if you see a paragraph that merits a point:
  * go to Cases and find the case you need
  * create the point for the service with that case
  * go back to the annotate view, reload the page, and assign the point to the quote.

So you need to have three tabs open, one to annotate, one to look up cases, and one to create points... :(

**Comment by Vinnl** [comment]
Perhaps it would be an idea to replace the list of points with a list of cases, and then create a new point for every annotation.

That means that the flow for creating new annotations from scratch would be made easier, which I'd say is desirable since that would (I think) be the preferred flow in the future and we'd want to hammer out issues there. In return, the flow for annotating existing points would become harder (select the appropriate case in the annotate view, then delete the original point with a comment referring to the annotation in a different tab).

**Comment by michielbdejong** [comment]
This was done.
