### ISSUE TITLE
Allow services, cases and documents to have a status `pending`

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#595]
This will allow us to open up the creation of services to more external contributors and allow them to approve each other's services, etc.

**Comment by michielbdejong** [comment]
we realized that just creating a weird case or service is a bit of a noop, since as soon as you add a point for it, that point would have to be approved before anything shows up. It would be possible for the creator of an item, or for any curator, to vandalize existing items, but we would still catch that in the manual export process, and when it happens, we can always just revert it. So closing this issue for now.
